#!/usr/bin/env python3
"""
build_site.py — Phase 4 scaffold helper for /recreate-website

Scaffolds the output directory structure and writes a starter index.html
skeleton based on the site analysis JSON. The actual HTML content is
filled in by Claude following the structure this script creates.

Usage:
    python build_site.py <site_analysis.json> <output_dir> [--stack <stack>]

    --stack options: html (default), react

Output:
    <output_dir>/
      index.html          — HTML skeleton with section stubs
      assets/css/styles.css  — CSS with custom properties from analysis
      assets/js/main.js   — JS stub with scroll reveal setup
      pages/              — Empty dir for sub-pages
      README.md           — Starter readme
"""

import sys
import os
import json
import argparse
from pathlib import Path


# ──────────────────────────────────────────────────────────────────────────────
# CSS skeleton builder
# ──────────────────────────────────────────────────────────────────────────────

def build_css(analysis: dict, site_name: str) -> str:
    design = analysis.get("visual_design", {})
    colors = design.get("colors", [])
    fonts = design.get("fonts", [])
    custom_props = design.get("css_custom_properties", {})

    # Pick up to 5 meaningful colors
    primary = colors[0] if len(colors) > 0 else "#0f172a"
    secondary = colors[1] if len(colors) > 1 else "#6366f1"
    accent = colors[2] if len(colors) > 2 else "#f59e0b"
    bg = colors[3] if len(colors) > 3 else "#ffffff"
    text = colors[4] if len(colors) > 4 else "#1e293b"

    font_stack = f"'{fonts[0]}', " if fonts else ""
    font_stack += "system-ui, -apple-system, sans-serif"

    custom_prop_lines = "\n".join(
        f"  {k}: {v};" for k, v in list(custom_props.items())[:20]
    )

    return f"""/* ============================================================
   {site_name} — Recreated Site Styles
   Generated by ui-ux-designer /recreate-website
   ============================================================ */

/* ── Custom Properties ──────────────────────────────────── */
:root {{
  /* Brand Colors (extracted from source site) */
  --color-primary:    {primary};
  --color-secondary:  {secondary};
  --color-accent:     {accent};
  --color-bg:         {bg};
  --color-bg-alt:     #f8fafc;
  --color-text:       {text};
  --color-text-muted: #64748b;
  --color-border:     #e2e8f0;

  /* Typography */
  --font-sans: {font_stack};
  --font-mono: 'JetBrains Mono', 'Fira Code', monospace;
  --text-xs:   0.75rem;
  --text-sm:   0.875rem;
  --text-base: 1rem;
  --text-lg:   1.125rem;
  --text-xl:   1.25rem;
  --text-2xl:  1.5rem;
  --text-3xl:  1.875rem;
  --text-4xl:  2.25rem;
  --text-5xl:  3rem;
  --text-6xl:  3.75rem;

  /* Spacing */
  --space-1:  0.25rem;
  --space-2:  0.5rem;
  --space-3:  0.75rem;
  --space-4:  1rem;
  --space-6:  1.5rem;
  --space-8:  2rem;
  --space-12: 3rem;
  --space-16: 4rem;
  --space-24: 6rem;
  --space-32: 8rem;

  /* Layout */
  --container-max: 1280px;
  --container-pad: var(--space-6);
  --section-pad-y: var(--space-24);

  /* Effects */
  --radius-sm: 0.375rem;
  --radius-md: 0.5rem;
  --radius-lg: 0.75rem;
  --radius-xl: 1rem;
  --radius-2xl: 1.5rem;
  --radius-full: 9999px;
  --shadow-sm:  0 1px 2px 0 rgb(0 0 0 / 0.05);
  --shadow-md:  0 4px 6px -1px rgb(0 0 0 / 0.1);
  --shadow-lg:  0 10px 15px -3px rgb(0 0 0 / 0.1);
  --shadow-xl:  0 20px 25px -5px rgb(0 0 0 / 0.1);
  --transition: 200ms cubic-bezier(0.4, 0, 0.2, 1);

  /* Source-extracted custom properties */
{custom_prop_lines}
}}

/* ── Reset ──────────────────────────────────────────────── */
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
html {{ scroll-behavior: smooth; -webkit-text-size-adjust: 100%; }}
body {{
  font-family: var(--font-sans);
  font-size: var(--text-base);
  line-height: 1.6;
  color: var(--color-text);
  background-color: var(--color-bg);
  -webkit-font-smoothing: antialiased;
}}
img, video {{ max-width: 100%; height: auto; display: block; }}
a {{ color: inherit; text-decoration: none; }}
button {{ cursor: pointer; border: none; background: none; font: inherit; }}

/* ── Layout ─────────────────────────────────────────────── */
.container {{
  max-width: var(--container-max);
  margin-inline: auto;
  padding-inline: var(--container-pad);
}}
.section {{
  padding-block: var(--section-pad-y);
}}
.section--alt {{
  background-color: var(--color-bg-alt);
}}
.grid-2 {{ display: grid; grid-template-columns: 1fr; gap: var(--space-8); }}
.grid-3 {{ display: grid; grid-template-columns: 1fr; gap: var(--space-6); }}
.grid-4 {{ display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-6); }}

@media (min-width: 768px) {{
  .grid-2 {{ grid-template-columns: repeat(2, 1fr); }}
  .grid-3 {{ grid-template-columns: repeat(2, 1fr); }}
}}
@media (min-width: 1024px) {{
  .grid-3 {{ grid-template-columns: repeat(3, 1fr); }}
  .grid-4 {{ grid-template-columns: repeat(4, 1fr); }}
  :root {{ --container-pad: var(--space-8); }}
}}

/* ── Typography ─────────────────────────────────────────── */
.heading-1 {{ font-size: clamp(2rem, 5vw, var(--text-6xl)); font-weight: 800; line-height: 1.1; letter-spacing: -0.02em; }}
.heading-2 {{ font-size: clamp(1.5rem, 3vw, var(--text-4xl)); font-weight: 700; line-height: 1.2; letter-spacing: -0.01em; }}
.heading-3 {{ font-size: clamp(1.25rem, 2vw, var(--text-2xl)); font-weight: 600; line-height: 1.3; }}
.lead {{ font-size: var(--text-xl); color: var(--color-text-muted); max-width: 600px; }}
.text-center {{ text-align: center; }}
.text-muted {{ color: var(--color-text-muted); }}

/* ── Buttons ────────────────────────────────────────────── */
.btn {{
  display: inline-flex; align-items: center; gap: var(--space-2);
  padding: 0.75rem 1.5rem;
  border-radius: var(--radius-md);
  font-size: var(--text-sm); font-weight: 600; letter-spacing: 0.01em;
  transition: all var(--transition);
  white-space: nowrap;
}}
.btn-primary {{
  background-color: var(--color-primary); color: #fff;
}}
.btn-primary:hover {{ opacity: 0.9; transform: translateY(-1px); box-shadow: var(--shadow-lg); }}
.btn-secondary {{
  background-color: transparent; color: var(--color-primary);
  border: 2px solid var(--color-primary);
}}
.btn-secondary:hover {{ background-color: var(--color-primary); color: #fff; }}
.btn-lg {{ padding: 1rem 2rem; font-size: var(--text-base); }}

/* ── Navigation ─────────────────────────────────────────── */
.nav {{
  position: sticky; top: 0; z-index: 100;
  background-color: var(--color-bg);
  border-bottom: 1px solid var(--color-border);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
}}
.nav__inner {{
  display: flex; align-items: center; justify-content: space-between;
  height: 64px;
}}
.nav__logo {{ font-weight: 800; font-size: var(--text-xl); color: var(--color-primary); }}
.nav__links {{ display: none; gap: var(--space-8); list-style: none; }}
.nav__links a {{ font-size: var(--text-sm); font-weight: 500; color: var(--color-text-muted); transition: color var(--transition); }}
.nav__links a:hover {{ color: var(--color-primary); }}
.nav__cta {{ display: none; }}
.nav__toggle {{ display: flex; flex-direction: column; gap: 4px; padding: var(--space-2); }}
.nav__toggle span {{ display: block; width: 22px; height: 2px; background: var(--color-text); transition: all var(--transition); }}
.nav__mobile {{ display: none; padding: var(--space-4); border-top: 1px solid var(--color-border); }}
.nav__mobile.is-open {{ display: block; }}
.nav__mobile ul {{ list-style: none; display: flex; flex-direction: column; gap: var(--space-4); }}
.nav__mobile a {{ font-size: var(--text-base); font-weight: 500; }}

@media (min-width: 768px) {{
  .nav__links, .nav__cta {{ display: flex; }}
  .nav__toggle {{ display: none; }}
}}

/* ── Hero ───────────────────────────────────────────────── */
.hero {{
  padding-block: var(--space-32);
  text-align: center;
  position: relative; overflow: hidden;
}}
.hero__eyebrow {{
  display: inline-block;
  font-size: var(--text-sm); font-weight: 600;
  color: var(--color-secondary);
  background: color-mix(in srgb, var(--color-secondary) 10%, transparent);
  padding: 0.25rem 0.75rem; border-radius: var(--radius-full);
  margin-bottom: var(--space-4);
}}
.hero__title {{ margin-bottom: var(--space-6); }}
.hero__subtitle {{ margin-inline: auto; margin-bottom: var(--space-8); }}
.hero__actions {{ display: flex; gap: var(--space-4); justify-content: center; flex-wrap: wrap; }}
.hero__image {{
  margin-top: var(--space-16);
  border-radius: var(--radius-2xl);
  overflow: hidden;
  box-shadow: var(--shadow-xl);
}}

/* ── Feature Cards ──────────────────────────────────────── */
.feature-card {{
  padding: var(--space-8);
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-xl);
  transition: all var(--transition);
}}
.feature-card:hover {{ box-shadow: var(--shadow-lg); border-color: var(--color-primary); transform: translateY(-2px); }}
.feature-card__icon {{
  width: 48px; height: 48px;
  background: color-mix(in srgb, var(--color-primary) 10%, transparent);
  border-radius: var(--radius-lg);
  display: flex; align-items: center; justify-content: center;
  margin-bottom: var(--space-4);
  font-size: 1.5rem;
}}
.feature-card__title {{ font-weight: 600; margin-bottom: var(--space-2); }}
.feature-card__desc {{ color: var(--color-text-muted); font-size: var(--text-sm); line-height: 1.7; }}

/* ── Social Proof / Testimonials ────────────────────────── */
.testimonial-card {{
  padding: var(--space-8);
  background: var(--color-bg-alt);
  border-radius: var(--radius-xl);
  border: 1px solid var(--color-border);
}}
.testimonial-card__quote {{ font-size: var(--text-lg); line-height: 1.7; margin-bottom: var(--space-6); color: var(--color-text); }}
.testimonial-card__author {{ display: flex; align-items: center; gap: var(--space-3); }}
.testimonial-card__avatar {{ width: 44px; height: 44px; border-radius: 50%; object-fit: cover; background: var(--color-border); }}
.testimonial-card__name {{ font-weight: 600; font-size: var(--text-sm); }}
.testimonial-card__role {{ font-size: var(--text-xs); color: var(--color-text-muted); }}
.stars {{ color: #f59e0b; letter-spacing: 0.05em; margin-bottom: var(--space-4); }}

/* ── CTA Banner ─────────────────────────────────────────── */
.cta-banner {{
  background: linear-gradient(135deg, var(--color-primary), var(--color-secondary));
  color: #fff; text-align: center;
  padding-block: var(--space-24);
  border-radius: var(--radius-2xl);
  margin-block: var(--space-16);
}}
.cta-banner .heading-2 {{ color: #fff; }}
.cta-banner .lead {{ color: rgba(255,255,255,0.8); margin-inline: auto; }}
.cta-banner .btn-primary {{ background: #fff; color: var(--color-primary); margin-top: var(--space-8); }}

/* ── Section Headers ────────────────────────────────────── */
.section-header {{ max-width: 640px; margin-inline: auto; text-align: center; margin-bottom: var(--space-16); }}
.section-header__label {{
  display: inline-block; font-size: var(--text-xs); font-weight: 700;
  letter-spacing: 0.1em; text-transform: uppercase;
  color: var(--color-secondary); margin-bottom: var(--space-3);
}}

/* ── Footer ─────────────────────────────────────────────── */
.footer {{
  background: var(--color-text); color: rgba(255,255,255,0.6);
  padding-block: var(--space-16);
  font-size: var(--text-sm);
}}
.footer a {{ color: rgba(255,255,255,0.6); transition: color var(--transition); }}
.footer a:hover {{ color: #fff; }}
.footer__grid {{
  display: grid; grid-template-columns: 1fr;
  gap: var(--space-12); margin-bottom: var(--space-12);
}}
.footer__brand {{ color: #fff; font-weight: 800; font-size: var(--text-xl); margin-bottom: var(--space-3); }}
.footer__col h4 {{ color: #fff; font-weight: 600; margin-bottom: var(--space-4); }}
.footer__col ul {{ list-style: none; display: flex; flex-direction: column; gap: var(--space-2); }}
.footer__bottom {{ padding-top: var(--space-8); border-top: 1px solid rgba(255,255,255,0.1); }}
@media (min-width: 768px) {{
  .footer__grid {{ grid-template-columns: 2fr 1fr 1fr 1fr; }}
}}

/* ── Animations ─────────────────────────────────────────── */
@media (prefers-reduced-motion: no-preference) {{
  .reveal {{
    opacity: 0; transform: translateY(24px);
    transition: opacity 0.6s ease, transform 0.6s ease;
  }}
  .reveal.is-visible {{ opacity: 1; transform: translateY(0); }}
  .reveal-delay-1 {{ transition-delay: 0.1s; }}
  .reveal-delay-2 {{ transition-delay: 0.2s; }}
  .reveal-delay-3 {{ transition-delay: 0.3s; }}
}}

/* ── Utilities ──────────────────────────────────────────── */
.sr-only {{ position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }}
.flex {{ display: flex; }}
.items-center {{ align-items: center; }}
.justify-between {{ justify-content: space-between; }}
.gap-4 {{ gap: var(--space-4); }}
.mt-auto {{ margin-top: auto; }}
.w-full {{ width: 100%; }}
"""


def build_js() -> str:
    return """// ============================================================
// main.js — /recreate-website generated JS
// ============================================================

// ── Scroll Reveal ─────────────────────────────────────────
const revealObserver = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('is-visible');
        revealObserver.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.1, rootMargin: '0px 0px -50px 0px' }
);

document.querySelectorAll('.reveal').forEach((el) => revealObserver.observe(el));

// ── Mobile Nav Toggle ─────────────────────────────────────
const toggle = document.querySelector('.nav__toggle');
const mobileMenu = document.querySelector('.nav__mobile');

if (toggle && mobileMenu) {
  toggle.addEventListener('click', () => {
    const isOpen = mobileMenu.classList.toggle('is-open');
    toggle.setAttribute('aria-expanded', isOpen);
  });
}

// ── Sticky Nav Shadow ─────────────────────────────────────
const nav = document.querySelector('.nav');
if (nav) {
  window.addEventListener('scroll', () => {
    nav.style.boxShadow = window.scrollY > 10
      ? '0 1px 12px rgb(0 0 0 / 0.08)'
      : 'none';
  }, { passive: true });
}

// ── Smooth Scroll for Anchor Links ────────────────────────
document.querySelectorAll('a[href^="#"]').forEach((link) => {
  link.addEventListener('click', (e) => {
    const target = document.querySelector(link.getAttribute('href'));
    if (target) {
      e.preventDefault();
      target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      // Close mobile menu if open
      mobileMenu?.classList.remove('is-open');
    }
  });
});
"""


def build_html_skeleton(analysis: dict, site_name: str) -> str:
    sections = analysis.get("structure", {}).get("sections_detected", [])
    colors = analysis.get("visual_design", {}).get("colors", [])
    fonts = analysis.get("visual_design", {}).get("fonts", [])

    has_gsap = "GSAP" in analysis.get("structure", {}).get("libraries_detected", [])
    gsap_cdn = '<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>\n  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>' if has_gsap else ""

    font_link = ""
    if fonts:
        safe_fonts = [f for f in fonts if "system" not in f.lower() and "sans-serif" not in f.lower()][:2]
        if safe_fonts:
            query = "+".join(f.replace(" ", "+") for f in safe_fonts) + ":wght@400;600;700;800"
            font_link = f'\n  <link rel="preconnect" href="https://fonts.googleapis.com">\n  <link href="https://fonts.googleapis.com/css2?family={query}&display=swap" rel="stylesheet">'

    # Build section stubs based on what was detected
    section_html = []
    if "header/nav" in sections or True:  # always include nav
        section_html.append("""
  <!-- ── Navigation ─────────────────────────────────────── -->
  <header class="nav" role="banner">
    <div class="container nav__inner">
      <a href="/" class="nav__logo" aria-label="Home">SiteName</a>
      <nav aria-label="Main navigation">
        <ul class="nav__links">
          <li><a href="#features">Features</a></li>
          <li><a href="#pricing">Pricing</a></li>
          <li><a href="#testimonials">Testimonials</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav>
      <div class="nav__cta">
        <a href="#" class="btn btn-primary">Get Started</a>
      </div>
      <button class="nav__toggle" aria-label="Toggle menu" aria-expanded="false">
        <span></span><span></span><span></span>
      </button>
    </div>
    <div class="nav__mobile" aria-label="Mobile navigation">
      <ul>
        <li><a href="#features">Features</a></li>
        <li><a href="#pricing">Pricing</a></li>
        <li><a href="#testimonials">Testimonials</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><a href="#" class="btn btn-primary w-full" style="text-align:center;">Get Started</a></li>
      </ul>
    </div>
  </header>""")

    # Hero always included
    section_html.append("""
  <!-- ── Hero ───────────────────────────────────────────── -->
  <section class="hero" id="hero" aria-labelledby="hero-title">
    <div class="container">
      <span class="hero__eyebrow"><!-- tagline / category --></span>
      <h1 class="heading-1 hero__title" id="hero-title">
        <!-- Benefit-focused headline here -->
      </h1>
      <p class="lead hero__subtitle">
        <!-- Supporting description -->
      </p>
      <div class="hero__actions">
        <a href="#" class="btn btn-primary btn-lg"><!-- Primary CTA --></a>
        <a href="#" class="btn btn-secondary btn-lg"><!-- Secondary CTA --></a>
      </div>
      <div class="hero__image reveal">
        <!-- Hero image or product screenshot -->
        <img src="" alt="" width="1280" height="720" loading="eager">
      </div>
    </div>
  </section>""")

    if "features" in sections:
        section_html.append("""
  <!-- ── Features ───────────────────────────────────────── -->
  <section class="section" id="features" aria-labelledby="features-title">
    <div class="container">
      <div class="section-header">
        <span class="section-header__label">Features</span>
        <h2 class="heading-2" id="features-title"><!-- Features headline --></h2>
        <p class="lead"><!-- Features subheadline --></p>
      </div>
      <div class="grid-3">
        <!-- Feature cards: add .reveal.reveal-delay-N for staggered animation -->
        <div class="feature-card reveal">
          <div class="feature-card__icon" aria-hidden="true">🚀</div>
          <h3 class="feature-card__title">Feature Title</h3>
          <p class="feature-card__desc">Feature description text.</p>
        </div>
        <!-- Repeat for each feature -->
      </div>
    </div>
  </section>""")

    if "testimonials" in sections:
        section_html.append("""
  <!-- ── Testimonials ────────────────────────────────────── -->
  <section class="section section--alt" id="testimonials" aria-labelledby="testimonials-title">
    <div class="container">
      <div class="section-header">
        <span class="section-header__label">What customers say</span>
        <h2 class="heading-2" id="testimonials-title"><!-- Testimonials headline --></h2>
      </div>
      <div class="grid-3">
        <div class="testimonial-card reveal">
          <div class="stars" aria-label="5 stars">★★★★★</div>
          <p class="testimonial-card__quote">"<!-- Quote text -->"</p>
          <div class="testimonial-card__author">
            <img class="testimonial-card__avatar" src="" alt="Reviewer name" width="44" height="44">
            <div>
              <div class="testimonial-card__name">Name</div>
              <div class="testimonial-card__role">Role, Company</div>
            </div>
          </div>
        </div>
        <!-- Repeat -->
      </div>
    </div>
  </section>""")

    if "pricing" in sections:
        section_html.append("""
  <!-- ── Pricing ─────────────────────────────────────────── -->
  <section class="section" id="pricing" aria-labelledby="pricing-title">
    <div class="container">
      <div class="section-header">
        <span class="section-header__label">Pricing</span>
        <h2 class="heading-2" id="pricing-title"><!-- Pricing headline --></h2>
        <p class="lead"><!-- Pricing subheadline --></p>
      </div>
      <!-- Pricing cards grid here -->
    </div>
  </section>""")

    if "faq" in sections:
        section_html.append("""
  <!-- ── FAQ ─────────────────────────────────────────────── -->
  <section class="section section--alt" id="faq" aria-labelledby="faq-title">
    <div class="container" style="max-width: 780px;">
      <div class="section-header">
        <span class="section-header__label">FAQ</span>
        <h2 class="heading-2" id="faq-title">Frequently Asked Questions</h2>
      </div>
      <div id="faq-list">
        <!-- FAQ items: <details><summary>Q?</summary><p>A.</p></details> -->
      </div>
    </div>
  </section>""")

    # CTA Banner always recommended
    section_html.append("""
  <!-- ── CTA Banner ──────────────────────────────────────── -->
  <section class="section" aria-label="Call to action">
    <div class="container">
      <div class="cta-banner reveal">
        <p class="section-header__label">Get started today</p>
        <h2 class="heading-2"><!-- CTA headline --></h2>
        <p class="lead"><!-- CTA supporting text --></p>
        <a href="#" class="btn btn-primary btn-lg"><!-- CTA button --></a>
      </div>
    </div>
  </section>""")

    section_html.append("""
  <!-- ── Footer ──────────────────────────────────────────── -->
  <footer class="footer" role="contentinfo">
    <div class="container">
      <div class="footer__grid">
        <div>
          <div class="footer__brand">SiteName</div>
          <p><!-- Brand tagline --></p>
        </div>
        <div class="footer__col">
          <h4>Product</h4>
          <ul>
            <li><a href="#">Features</a></li>
            <li><a href="#">Pricing</a></li>
          </ul>
        </div>
        <div class="footer__col">
          <h4>Company</h4>
          <ul>
            <li><a href="#">About</a></li>
            <li><a href="#">Blog</a></li>
          </ul>
        </div>
        <div class="footer__col">
          <h4>Legal</h4>
          <ul>
            <li><a href="#">Privacy</a></li>
            <li><a href="#">Terms</a></li>
          </ul>
        </div>
      </div>
      <div class="footer__bottom">
        <p>&copy; 2025 SiteName. All rights reserved.</p>
      </div>
    </div>
  </footer>""")

    sections_str = "\n".join(section_html)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <title>{site_name}</title>
  <link rel="icon" type="image/svg+xml" href="/assets/images/favicon.svg">{font_link}
  <link rel="stylesheet" href="/assets/css/styles.css">
  <!-- Open Graph -->
  <meta property="og:title" content="{site_name}">
  <meta property="og:description" content="">
  <meta property="og:type" content="website">
</head>
<body>
{sections_str}

  {gsap_cdn}
  <script src="/assets/js/main.js" defer></script>
</body>
</html>
"""


# ──────────────────────────────────────────────────────────────────────────────
# README
# ──────────────────────────────────────────────────────────────────────────────

def build_readme(site_name: str, analysis: dict) -> str:
    libs = analysis.get("structure", {}).get("libraries_detected", [])
    return f"""# {site_name} — Recreated

Generated by **ui-ux-designer** `/recreate-website` skill.

## Overview

This is a recreated and improved version of the original {site_name} site,
rebuilt with semantic HTML5, CSS custom properties, and vanilla JavaScript.

## Tech Stack

- **HTML5** — Semantic structure, ARIA labels, proper heading hierarchy
- **CSS** — Custom properties, mobile-first responsive, no build step needed
- **JavaScript** — Vanilla JS, Intersection Observer for scroll reveals
{("- **GSAP** — Complex animation timelines" + chr(10)) if "GSAP" in libs else ""}
## Running Locally

```bash
# Option 1: Any static server
npx serve .

# Option 2: Python
python -m http.server 8000

# Option 3: VS Code Live Server extension — right-click index.html → Open with Live Server
```

Then open [http://localhost:8000](http://localhost:8000)

## Structure

```
.
├── index.html          Main page
├── assets/
│   ├── css/styles.css  All styles (CSS custom properties)
│   ├── js/main.js      Interactions: scroll reveal, mobile nav
│   └── images/
│       ├── manifest.json       Image generation record
│       └── pending-generation.md  Failed images that need manual retry
├── pages/              Sub-pages (if crawled)
└── README.md           This file
```

## Image Manifest

See `assets/images/manifest.json` for the full list of AI-generated images,
their prompts, and permanent imgbb URLs.

If there are failed generations, see `assets/images/pending-generation.md`
for the prompts to retry manually at https://kie.ai.

## Competitive Analysis

See `analysis/competitive_analysis.md` for a full breakdown of
competitor patterns and the improvements applied.

## Improvements Applied

See the competitive analysis file for a documented list of every change
and the research insight that motivated it.

## Manual Steps

- Replace `SiteName` in HTML/CSS with the actual brand name
- Fill in all HTML comment placeholders with real content
- Retry any pending image generations from `pending-generation.md`
- Update `<meta name="description">` with real SEO copy
- Add real favicon at `assets/images/favicon.svg`
"""


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def scaffold(analysis_file: str, output_dir: str, stack: str = "html"):
    analysis = json.loads(Path(analysis_file).read_text())
    out = Path(output_dir)

    # Infer site name from headings or URL
    headings = analysis.get("content", {}).get("headings", [])
    h1 = next((h["text"] for h in headings if h["level"] == "h1"), None)
    site_name = h1[:40] if h1 else "Recreated Site"

    # Create dirs
    (out / "assets" / "css").mkdir(parents=True, exist_ok=True)
    (out / "assets" / "js").mkdir(parents=True, exist_ok=True)
    (out / "assets" / "images").mkdir(parents=True, exist_ok=True)
    (out / "pages").mkdir(parents=True, exist_ok=True)
    (out / "analysis").mkdir(parents=True, exist_ok=True)

    # Write files
    (out / "index.html").write_text(build_html_skeleton(analysis, site_name))
    (out / "assets" / "css" / "styles.css").write_text(build_css(analysis, site_name))
    (out / "assets" / "js" / "main.js").write_text(build_js())
    (out / "README.md").write_text(build_readme(site_name, analysis))

    print(f"[build_site] Scaffolded → {out}")
    print(f"  index.html")
    print(f"  assets/css/styles.css")
    print(f"  assets/js/main.js")
    print(f"  README.md")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scaffold recreated site")
    parser.add_argument("analysis_file", help="Path to site_analysis.json")
    parser.add_argument("output_dir", help="Output directory")
    parser.add_argument("--stack", default="html", choices=["html", "react"])
    args = parser.parse_args()

    import argparse  # ensure it's available (it's imported above but guard)
    scaffold(args.analysis_file, args.output_dir, args.stack)
